### ISSUE TITLE
Mac M1 support

### ISSUE THREAD

**Issue by Inaztm** [jmgomez/NimTemplate#3]
On Mac M1 not compile.

Command:
```
nimble setup
```
Error:

<img width="995" alt="image" src="https://user-images.githubusercontent.com/9611099/229201166-62f5dc0e-2365-4009-a62b-62d67d85ac49.png">

**Comment by jmgomez** [comment]
You are attempting to compile it with arch == "arm64" (you can check it out by typing arch in the cmd line) but unreal 5.1 used x86 to build that PCH (and the dynlibs). 

Check out the answer here https://developer.apple.com/forums/thread/718666 and make sure you invoked Nim from Intel
