### ISSUE TITLE
The "./nue setup" fails on Windows due to PCG plugin

### ISSUE THREAD

**Issue by Xkonti** [jmgomez/NimTemplate#5]
Environment:
- Windows 11
- Nim Compiler Version 2.1.1 [`devel`, Windows: amd64] - Compiled at 2024-05-05
- Nimble v0.14.2 - Compiled at 2024-05-05
- Unreal Engine 5.4.1

Steps to recreate:
1. ✅ Update Nim by running `choosenim update devel` and `choosenim devel`
2. ✅ Switch working directory to `D:/ue`
3. ✅ Clone template: `git clone https://github.com/jmgomez/NimTemplate.git --recurse-submodules`
4. ✅ Navigated to the plugin dir: `cd NimTemplate/Plugins/NimForUE`
5. ✅ Setup nue: `nimble nue`
6. ❌ The `NimForUE.win.json` failed to generate. Manually created one from `NimForUE.win.sample.json` with corrected paths:
    ```json
    {
      "engineDir": "C:\\Program Files\\Epic Games\\UE_5.4\\Engine",
      "gameDir": "D:\\ue\\NimTemplate",
      "targetConfiguration": "Development",
      "targetPlatform": "Win64",
      "withEditor": true
    }
    ```
7. ❌ Ran `./nue setup` and encountered the following error:
    ```
    LINK : fatal error LNK1181: cannot open input file 'C:\\Program Files\\Epic Games\\UE_5.4\\Engine\\Plugins\\Experimental\\PCG\\Intermediate\\Build\\Win64\\x64\\UnrealEditor\\Development\\PCG\\UnrealEditor-PCG.lib'
    Error: execution of an external program failed: 'vccexe.exe  @nimforue_linkerArgs.txt'
    nue.nim                  nue
    nue.nim                  main
    nue.nim                  setup
    nue.nim                  guest
    nuecompilation.nim       compilePlugin
    assertions.nim           failedAssertImpl
    assertions.nim           raiseAssert
    fatal.nim                sysFatal
    Error: unhandled exception: nuecompilation.nim(132, 11) `execCmd(compCmd) == 0`  [AssertionDefect]
    ```

Full console output attached to the issue: [nue_setup_logs.txt](https://github.com/jmgomez/NimTemplate/files/15222540/nue_setup_logs.txt)

**Comment by Xkonti** [comment]
Looks like the `PCG` plugin has been moved out of Experimental in 5.4 and now resides in `Engine/Plugins` instead of `Engine/Plugins/Experimental`.

**Comment by jmgomez** [comment]
> Looks like the `PCG` plugin has been moved out of Experimental in 5.4 and now resides in `Engine/Plugins` instead of `Engine/Plugins/Experimental`.

Yes, this is already handled in `nimforueconfig.nim`. Updated the project to use 5.4 instead of 5.3. Feel free to close this issue once you confirm it works in your end (works in mine)

**Comment by Xkonti** [comment]
This made the `.nue setup` complete successfully and the whole project seems to work properly on UE 5.4.1. Thank you!
